a = input("Digite algo: ")
print("O tipo primitivo desse valor é ",type(a))
print("Só tem espaços? ", a.isspace())
print("É alfabético? ",a.isalpha())
print('É um número? ',a.isnumeric())
print('É alfanúmerico ?',a.isalnum())
print('Esta em minuscolas? ',a.islower())
print('Esta em maiusculas? ', a.isupper())
