times = ('Corinthians','Palmeiras','Santos','Grêmio','Cruzeiro','Flamengo','Vasco da Gama','Chapecoense','Atlético-MG','Botafogo','Athletico-PR','Bahia','São Paulo','Fluminense','Sport Recife','EC Vitória','Coritiba','Avaí','Ponte Preta','Atlético-GO')
print(f'Lista da época de futebol de 2017 (Brasil): {times}',)
print('=='*50)
print(f'Os 5 primeiros colocados: {times[:5]}')
print('=='*50)
print(f'Os ultimos 4 colocados: {times[-4:]}')
print('=='*50)
print(f'Times em ordem alfabética: {sorted(times)}')
print('=='*50)
print(f'O Chapecoense está na {times.index("Chapecoense")+1}ª posição')
print('=='*50)